#theme: jekyll-theme-cayman

title: Sports scoreboard for streaming on Mac
description: Broadcasts with statistics via OBS, WireCast, Streamlabs, etc.

plugins:
  - jekyll-feed

#theme: minima
remote_theme: jekyll/minima

minima:
  skin: auto

header_pages:
  # - guides.md
  - PRIVACY_POLICY.md
  - support.md
